#!/bin/sh

# Set these paths appropriately

BIN=/home/christophe/Documents/code/library/treeTagger/bin
CMD=/home/christophe/Documents/code/library/treeTagger/cmd
LIB=/home/christophe/Documents/code/library/treeTagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
