#!/bin/sh

# Set these paths appropriately

BIN=/home/christophe/Documents/code/library/treeTagger/bin
CMD=/home/christophe/Documents/code/library/treeTagger/cmd
LIB=/home/christophe/Documents/code/library/treeTagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
