#!/bin/sh

# Set these paths appropriately

BIN=/home/christophe/Documents/code/library/treeTagger/bin
CMD=/home/christophe/Documents/code/library/treeTagger/cmd
LIB=/home/christophe/Documents/code/library/treeTagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/italian-abbreviations
PARFILE=${LIB}/italian-utf8.par

$TOKENIZER -i -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
